### ISSUE TITLE
Monitoring shows wrong amount of RAM

### ISSUE THREAD

**Issue by igorkulman** [xibbon/LaTerminal#54]
On my Ubuntu 22.04.1 LTS server I have 12 GB RAM, as seen in htop

<img width="885" alt="Screenshot 2023-02-16 at 21 49 57" src="https://user-images.githubusercontent.com/4746070/219484698-814c8240-abed-40c3-b662-03cd019551d0.png">

but the monitoring in La Terminal shows the correct amount of RAM used, 1.46 GB, but it thinks the total ram is something like 1.6 GB only not 12 GB

![IMG_6135](https://user-images.githubusercontent.com/4746070/219484864-8d83805d-9df6-4e89-9475-05c63c1a3660.PNG)

showing the RAM as 98% used which is not true

**Comment by migueldeicaza** [comment]
Thank you for this detailed bug report, luckily I have a VM with almost the same configuration.

I believe the issue is that I am not showing the memory that is in use by the buffer cache, which is technically memory the kernel can use at will, but is also in use.  So it is kind of in limbo, and I am not showing it, so I will add this.

Thanks for this bug report!

**Comment by migueldeicaza** [comment]
Implemented
